version: '3.3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: dm/server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - dm-net

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: dm/webapp
    container_name: webapp
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - dm-net
      
  nginx:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    image: dm/nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - DM_HOST=${DM_HOST:-localhost}
    depends_on:
      - server
      - webapp
    networks:
      - dm-net


networks:
   dm-net:
     driver: bridge